# -*- coding: utf-8 -*-
"""DL_LAB_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TMGEjFmqLDPUQqb7NhQdbMomAQ-n5zR8
"""

import tensorflow as tf
x_con=tf.constant ([1,2,3,4])
x_var=tf.Variable(x_con)
print(x_var)
print(tf.rank(x_con))

import tensorflow as tf
import numpy as np
x_var = tf.Variable([1, 2, 3, 4])
x_var_numpy = x_var.numpy()
print("NumPy Array:", x_var_numpy)
print("Rank using NumPy:", np.ndim(x_var_numpy))

import tensorflow as tf
a=tf.Variable([1,2,3,4])
b=tf.Variable([4,5,6,7])
x=tf.add(a,b)
x_numpy=x.numpy()
print("Rank using NumPy:", np.ndim(x_numpy))
print(x)

import tensorflow as tf
import numpy as np
a = tf.Variable([[1, 2, 3, 4]])
b = tf.Variable([[4], [5], [6], [7]])
x = tf.matmul(a, b)
print(x)

import tensorflow as tf
import numpy as np
a = tf.Variable([[1, 2, 3, 4],[6,7,8,9]])
b = tf.Variable(([[4, 5], [6, 7], [9, 10], [11, 12]]))
x = tf.matmul(a, b)
print(x)